### ISSUE TITLE
Issue with Broker

### ISSUE THREAD

**Issue by sastry17** [Jc2k/hpfeeds3#11]
Hi, when i try to subscribe to the broker, i see that the owner and the ident fields are read as **none**. 

![image](https://user-images.githubusercontent.com/58994291/89389996-6e635280-d706-11ea-8648-b451a1bd7933.png)

**Comment by Jc2k** [comment]
Hi - i'm in the process of archiving hpfeeds3 as all the patches are upstream in hpfeeds itself (https://github.com/hpfeeds/hpfeeds) and in the hpfeeds package on pypi (https://pypi.org/project/hpfeeds/).

It's actually normal for those fields to be `None` until an authentication has been successfully completed. So that is likely not the root of your problem.

Can you provide more information on your setup and on what is happening and i might be able to think of something you can try?

**Comment by sastry17** [comment]
The setup is on an Ubuntu 18.04 OS. I am currently testing the broker and the subscriber on the same machine. I would like to use mongodb for the auth store, but however, wanted to first test with the default sqlite db. I have created the users in the relevant table.

**Comment by sastry17** [comment]
This is the subscriber side:

![image](https://user-images.githubusercontent.com/58994291/89394612-91910080-d70c-11ea-90d1-d92e12562e26.png)

**Comment by Jc2k** [comment]
Thanks. I need as much detail as you are able to provide - imagine you were writing a setup document for an underling and you wanted them to arrive at an identical setup to you, with the same versions.

In particular i really need to know:

Are you using the command line client that ships with hpfeeds? Or is this custom code? What are you using for the subscriber?

You mentioned about mongo - but the hpfeeds3 broker never had mongo built in. So i need to check which broker you are using. The upstream version got mongo support recently for example, but you raised the issue here. So are you using hpfeeds3 for the cliennt and hpfeeds itself for the broker? How are you runing the broker? Docker? Which image?

There was a bug in the broker where if owner was blank, authentication would fail. So i'd also like to check that none of the fields are blank.

If you aren't planning to use sqlite in production then there are 2 simpler auth backends you can also try - [JSON](https://python.hpfeeds.org/en/latest/broker.html#json-authentication-store) and [env variables](https://python.hpfeeds.org/en/latest/broker.html#super-easy-throwaway-test-broker).

And what you think the problem actually is. What i'm really looking for is the symptoms. Is the client hanging? Giving an error about auth? Does publishing seem to work but subscriber is not seeing anything? What is happening or not happening that made you raise a ticket?

So far what i'm trying to reproduce is "it doesn't work and the problem happens before authentication is completed" but i don't really know what the "it doesnt work" bit means.

**Comment by Jc2k** [comment]
Crossed the streams!

That error means that the ident is not in the sqlite database or the secret doesn't match.

Maybe try the JSON or env auth backend. I use the JSON backend on kubernetes.

**Comment by sastry17** [comment]
ok sure, will try that! Thanks a lot for the quick response! :)

**Comment by sastry17** [comment]
@Jc2k 

Sorry to bother you my friend, all is good. It works with json backend. 

I just wanted to know about the support for mongodb, which i will try now. I will close this issue. Thanks for your support!

**Comment by Jc2k** [comment]
No problem, glad to help! I'm about to archive this repo but i'm also responding upstream at https://github.com/hpfeeds/hpfeeds if you need any more help!
