### ISSUE TITLE
Change License to Apache 2

### ISSUE THREAD

**Issue by omercnet** [Jc2k/hpfeeds3#4]
Any particular reason this is licensed under GPLv3 and not something friendlier like MIT or Apache?

**Comment by Jc2k** [comment]
This is indeed on my personal roadmap.

Rest assured that all the code I have added I consider to be Apache 2, but i'm allowing it to be shipped in this repo under GPL3 to respect the upstream licence.

No matter how much I have added the original code (the client and the protocol parser and serializer) is still a fork and has to comply with the upstream licence. At the moment that means I can't slap a licence on it and call this done. To do this properly I need to reach out to all the contributors who still have code in the current upstream, and will start doing that soon.

**Comment by omercnet** [comment]
ah I didn't realize the original repo was GPL3

I look forward to this change, please update your progress here and let me know if I can help in any way

**Comment by Jc2k** [comment]
Wow I can't believe it was 2018 when we talked about this... All of my changes did make it upstream, and the `hpfeeds` package on pypi is up to date. I haven't had chance to chase this, though. I have opened https://github.com/hpfeeds/hpfeeds/issues/64 to track it upstream.

I'm going to archive this repo now, because it's attracting tickets that should be going upstream.
